### ISSUE TITLE
When a catch all '*' url is matched the path is updated with a prefix %2F

### ISSUE THREAD

**Issue by garth** [cerebral/cerebral-module-router#57]
http://localhost:3000/invalid is matched by `{ '*': 'notFoundRouted' }` and the url updates to http://localhost:3000/%2Finvalid.

**Comment by christianalfoni** [comment]
I suppose @Guria should have a saying on this :-)

**Comment by Guria** [comment]
Of course. Will test it and release a fix

**Comment by Guria** [comment]
I've remembered. `path-to-regexp` catches `/` as value. I've [supposed to use `/*`](https://github.com/cerebral/cerebral-router/blob/master/tests/browser.js#L559) for catch all instead of just `*`. Would it fit for all if documented of course?I've remembered. `path-to-regexp` catches `/` as value. I've [supposed to use `/*`](https://github.com/cerebral/cerebral-router/blob/master/tests/browser.js#L559) for catch all instead of just `*`. Would it fit for all if documented of course?

**Comment by garth** [comment]
Previous version of router used '*', so should probably be documented as breaking change.

**Comment by Guria** [comment]
documented in readme
