### ISSUE TITLE
Passing an integer to a route signal can create strange urls

### ISSUE THREAD

**Issue by NervosaX** [cerebral/cerebral-module-router#68]
Obviously very minor, as it's merely how the url looks. I have the following action:

```javascript
export function navigateToAppointment({ input, services }) {
	services.router.redirectToSignal("appointments.detail.detailsTabOpened", {
		id: input.id
	});
}
```

Where the input.id is an integer. After routing, the url looks like this:
`http://nervosa:6533/#/appointments/%3A119/detail`

If I toString() the value however it looks like:
`http://nervosa:6533/#/appointments/120/detail` which is much easier to debug. Both urls work as expected however, but I can't think of a good reason where a route would ever want an input that is not a string, and it's better to not have to worry about these formatting issues. Perhaps all values passed to the router should be cast to a string?

**Comment by Guria** [comment]
https://github.com/cerebral/url-mapper#stringify-method
> Properties defined in route are stringified to path part using `path-to-regexp` module, tweaked to support `Boolean` and `Number`. Properties not defined in route are stringified to query part using `URLON` module if `{ query: true }` option was passed to factory.

@NervosaX I know it is questionable, but actually it is by design to preserve type of value.

My point is that when router attached to existing signals it shouldn't break the way how it works.
If router triggered with `/appointments/120/detail` url `input.id` would be a string `'120'`. We can't be sure that it wouldn't break anything and/or action makes a proper type conversion on that input.

If you are sure that your action is ok to receive string, and you want to make your url look better, just pass a string value to signal.

Though I would prefer if url would appear as `/appointments/:120/detail` in case of integers and booleans, but wasn't able to override [`path-to-regexp`'s compile method applies `encodeURIComponent`](https://github.com/pillarjs/path-to-regexp/blob/master/index.js#L171) to it.

**Comment by NervosaX** [comment]
I will convert my integers to strings then, but I think I will often forget to. Could it maybe be an option on the router (and on url-mapper) to change how that works?

**Comment by Guria** [comment]
I will think on it

**Comment by christianalfoni** [comment]
Hm, I think this has to be up to the developer. If your ids are type number, but you want to show them as strings, you cast them as strings when firing off the payload. But yeah, its a gotcha

**Comment by bfitch** [comment]
I ran into this too. My only objection is that most "normal" routers will stringify by default, right? Perhaps it's only a documentation thing, but did surprise me. 😀

**Comment by Guria** [comment]
documented in readme
